name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd-pipeline
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install flake8 black pytest

      - name: Run flake8 linter
        run: flake8 src tests

      - name: Format code with Black
        run: black --check src tests

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests